Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -10,10 +10,11 @@
 #   - PHP Coding Standards Fixer (PHP CS Fixer) (https://github.com/FriendsOfPHP/PHP-CS-Fixer)
 #   - PHP Mess Detector (PHPMD) (https://phpmd.org/)
 #   - PHP Copy/Paste Detector (PHPCPD) (https://github.com/sebastianbergmann/phpcpd)
+#   - PHP Unit Testing (https://github.com/sebastianbergmann/phpunit)
 #
 ##########
 
-    cat <<\EOF
+cat <<\EOF
 
     ____                                                 _ __
    / __ \________        _________  ____ ___  ____ ___  (_) /_
@@ -24,12 +25,11 @@ EOF
 
 echo
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-    against=HEAD
+if git rev-parse --verify HEAD >/dev/null 2>&1; then
+  against=HEAD
 else
-    # Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+  # Initial commit: diff against an empty tree object
+  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -42,13 +42,12 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-    # Note that the use of brackets around a tr range is ok here, (it's
-    # even required, for portability to Solaris 10's /usr/bin/tr), since
-    # the square bracket bytes happen to fall in the designated range.
-    test $(git diff --cached --name-only --diff-filter=A -z $against |
-      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-    cat <<\EOF
+  # Note that the use of brackets around a tr range is ok here, (it's
+  # even required, for portability to Solaris 10's /usr/bin/tr), since
+  # the square bracket bytes happen to fall in the designated range.
+  test $(git diff --cached --name-only --diff-filter=A -z $against |
+    LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0; then
+  cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -59,7 +58,7 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-    exit 1
+  exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
@@ -124,19 +123,19 @@ color_reset='\033[0m'
 ###########
 
 function message_failure() {
-    printf "${color_bold_white}${color_background_red} 🤦  $1 ${color_reset}\n"
+  printf "${color_bold_white}${color_background_red} 🤦  $1 ${color_reset}\n"
 }
 
 function message_success() {
-    printf "${color_bold_black}${color_background_green} $1 🍺  ${color_reset}\n"
+  printf "${color_bold_black}${color_background_green} $1 🍺  ${color_reset}\n"
 }
 
 function message_warning() {
-    printf "${color_bold_black}${color_background_yellow} ⚠️ $1 ${color_reset}\n"
+  printf "${color_bold_black}${color_background_yellow} ⚠️ $1 ${color_reset}\n"
 }
 
 function message_info() {
-    printf "${color_bold_black}${color_background_blue} ☝️️  $1 ${color_reset}\n"
+  printf "${color_bold_black}${color_background_blue} ☝️️  $1 ${color_reset}\n"
 }
 
 ######################
@@ -157,11 +156,10 @@ files=$(git diff --cached --name-only --diff-filter=ACM $against | grep '\.php$'
 project=$(git rev-parse --show-toplevel)
 
 # Apenas caminhos e nomes dos arquivos: /path/file.php,/foo/file.php,/bar/file.php
-for relative_file_path in $files
-do
-    staged_files="$staged_files $(git rev-parse --show-toplevel)/$relative_file_path"
-    # file_name=$(basename "$relative_file_path")
-    # file_entension=${file_name##*.}
+for relative_file_path in $files; do
+  staged_files="$staged_files $(git rev-parse --show-toplevel)/$relative_file_path"
+  # file_name=$(basename "$relative_file_path")
+  # file_entension=${file_name##*.}
 done
 
 # Replace first blank only
@@ -176,163 +174,219 @@ staged_files_separated_by_comma=${staged_files// /,}
 
 if [ -n "$files" ]; then
 
-    echo "╭──────────────────────────────────╮"
-    printf "|〈〈〈 ${color_bold_white}Checking PHP Lint...${color_reset} 〉〉〉|\n"
-    echo "╰──────────────────────────────────╯"
+  echo "╭──────────────────────────────────╮"
+  printf "|〈〈〈 ${color_bold_white}Checking PHP Lint...${color_reset} 〉〉〉|\n"
+  echo "╰──────────────────────────────────╯"
+  echo
+
+  # Check for errors when running PHP LINT.
+  php_lint_errors=false
+
+  for file in $files; do
+
+    # Check if they are valid php files.
+    php_lint_output=$(php -l -d display_errors=On $file 2>&1 | grep 'PHP Parse error:')
+
+    # If it did contain errors, we have output.
+    if [ -n "$php_lint_output" ]; then
+      # Printing error message.
+      message_failure "$php_lint_output"
+
+      # Adding error message.
+      errors=("${errors[@]}" "$php_lint_output")
+
+      php_lint_errors=true
+    fi
+  done
+
+  if [ "$php_lint_errors" = false ]; then
+    message_success 'No Errors Found - PHP Lint(Syntax check only)'
+  else
+    exit 1
+  fi
+
+  echo
+  echo "╭─────────────────────────────────────────────────╮"
+  printf "|〈〈〈 ${color_bold_white}PHP Coding Standards Fixer(PSR2)...${color_reset} 〉〉〉|\n"
+  echo "╰─────────────────────────────────────────────────╯"
+  echo
+
+  message_info "Running PHP Code Sniffer..."
+  echo
+
+  # Verificando se arquivo binário executável existe para [php-cs-fixer].
+  if ! hash php-cs-fixer 2>/dev/null; then
+    message_warning "No valid PHP Coding Standards Fixer executable found! Please have one available as either ✖✖✖ php-cs-fixer ✖✖✖"
+    message_info "Visit: https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation"
     echo
+    exit 1
+  fi
 
-    # Check for errors when running PHP LINT.
-    php_lint_errors=false
+  printf "${color_bold_yellow}✔︎ Rules: PSR1, PSR2, Symfony, PhpCsFixer, PHP73Migration${color_reset}\n"
+  printf "${color_bold_yellow}✔︎ Using Cache: No${color_reset}\n"
+  printf "${color_bold_yellow}✔︎ Output Format: Text(default)${color_reset}\n"
+  echo
 
-    for file in $files; do
+  git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
+    # php-cs-fixer CHECK.
+    # --dry-run (The --dry-run option displays the files that need to be fixed but without actually modifying them).
+    php_cs_fixer_codestyle_dry_run=$(php-cs-fixer --dry-run --diff --verbose --using-cache=no --rules=@PSR1,@PSR2,,@Symfony,@Symfony,@PhpCsFixer,@PHP73Migration fix ${line} 2>&1 | grep "diff")
 
-        # Check if they are valid php files.
-        php_lint_output=`php -l -d display_errors=On $file 2>&1 | grep 'PHP Parse error:'`
+    # Check last command (PHP-CS-FIXER) code for fixed.
+    if [ -n "$php_cs_fixer_codestyle_dry_run" ]; then
 
-        # If it did contain errors, we have output.
-        if [ -n "$php_lint_output" ]; then
-            # Printing error message.
-            message_failure "$php_lint_output"
+      # Applicando PSRs e @Symfony.
+      php_cs_fixer_codestyle=$(php-cs-fixer --diff --using-cache=no --rules=@PSR1,@PSR2,,@Symfony,@Symfony,@PhpCsFixer,@PHP73Migration fix ${line} &>/dev/null)
 
-            # Adding error message.
-            errors=("${errors[@]}" "$php_lint_output")
+      git add ${line}
 
-            php_lint_errors=true
-        fi
-    done
-
-    if [ "$php_lint_errors" = false ]; then
-        message_success 'No Errors Found - PHP Lint(Syntax check only)'
+      message_info "GIT ADD + PHP Coding Standards Fixer fixing: [ ${line} ]"
     else
-        exit 1
+      printf "${color_bold_yellow}File already ${color_background_yellow}${color_bold_black}FIXED${color_reset}${color_bold_yellow} and also already added to the ${color_background_yellow}${color_bold_black}GIT${color_reset} ➨ ${color_bold_white}${color_underline_white}${line}${color_reset}\n"
     fi
+  done
 
-    echo
-    echo "╭─────────────────────────────────────────────────╮"
-    printf "|〈〈〈 ${color_bold_white}PHP Coding Standards Fixer(PSR2)...${color_reset} 〉〉〉|\n"
-    echo "╰─────────────────────────────────────────────────╯"
-    echo
+  echo
+  echo "╭──────────────────────────────────────────╮"
+  printf "|〈〈〈 ${color_bold_white}PHPMD - PHP Mess Detector...${color_reset} 〉〉〉|\n"
+  echo "╰──────────────────────────────────────────╯"
+  echo
 
-    message_info "Running PHP Code Sniffer..."
-    echo
+  phpmd_command="phpmd"
 
-    # Verificando se arquivo binário executável existe para [php-cs-fixer].
-    if ! hash php-cs-fixer 2>/dev/null; then
-        message_warning "No valid PHP Coding Standards Fixer executable found! Please have one available as either ✖✖✖ php-cs-fixer ✖✖✖"
-        message_info "Visit: https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation"
-        echo
-        exit 1
-    fi
-
-    printf "${color_bold_yellow}✔︎ Rules: PSR1, PSR2, Symfony, PhpCsFixer, PHP73Migration${color_reset}\n"
-    printf "${color_bold_yellow}✔︎ Using Cache: No${color_reset}\n"
-    printf "${color_bold_yellow}✔︎ Output Format: Text(default)${color_reset}\n"
-    echo
-
-    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
-        # php-cs-fixer CHECK.
-        # --dry-run (The --dry-run option displays the files that need to be fixed but without actually modifying them).
-        php_cs_fixer_codestyle_dry_run=`php-cs-fixer --dry-run --diff --verbose --using-cache=no --rules=@PSR1,@PSR2,,@Symfony,@Symfony,@PhpCsFixer,@PHP73Migration fix ${line} 2>&1 | grep "diff"`
-
-        # Check last command (PHP-CS-FIXER) code for fixed.
-        if [ -n "$php_cs_fixer_codestyle_dry_run" ]; then
-
-            # Applicando PSRs e @Symfony.
-            php_cs_fixer_codestyle=`php-cs-fixer --diff --using-cache=no --rules=@PSR1,@PSR2,,@Symfony,@Symfony,@PhpCsFixer,@PHP73Migration fix ${line} &>/dev/null`
-
-            git add ${line}
-
-            message_info "GIT ADD + PHP Coding Standards Fixer fixing: [ ${line} ]"
-        else
-            printf "${color_bold_yellow}File already ${color_background_yellow}${color_bold_black}FIXED${color_reset}${color_bold_yellow} and also already added to the ${color_background_yellow}${color_bold_black}GIT${color_reset} ➨ ${color_bold_white}${color_underline_white}${line}${color_reset}\n"
-        fi
-    done
-
-    echo
-    echo "╭──────────────────────────────────────────╮"
-    printf "|〈〈〈 ${color_bold_white}PHPMD - PHP Mess Detector...${color_reset} 〉〉〉|\n"
-    echo "╰──────────────────────────────────────────╯"
-    echo
-
-    if ! hash phpmd 2>/dev/null; then
-        message_warning "No valid PHP Mess Detector executable found! Please have one available as either ✖✖✖ phpmd ✖✖✖"
-        message_info "Visit: https://phpmd.org/download/index.html"
-        echo
-        exit 1
-    fi
-
-    # @see https://phpmd.org/rules/index.html
-    phpmd_rules="cleancode,codesize,controversial,design,naming,unusedcode"
-
-    printf "✔︎ Report Format: ${color_bold_yellow}text${color_reset}\n"
-    printf "✔︎ Ruleset Files: ${color_bold_yellow}${phpmd_rules}${color_reset}\n"
-    printf "✔︎ Suffixes: ${color_bold_yellow}php${color_reset}\n"
-    echo
-
-    message_info "PHPMD - PHP Mess Detector: [ ${staged_files_separated_by_comma} ]"
-
-    # PHPMD running script
-    phpmd_output=$(phpmd ${staged_files_separated_by_comma} text "${phpmd_rules}" --suffixes php)
-    phpmd_retval=$?
-
-    if [ $phpmd_retval -ne 0 ]; then
-        echo
-        message_failure "PHPMD - PHP Mess Detector found some errors. Fix the errors before commit."
-
-        printf "${phpmd_output}\n"
-
-        # Adding error message.
-        errors=("${errors[@]}" "$phpmd_output")
+  # Check vendor/bin/phpmd
+  phpmd_vendor_command="vendor/bin/phpmd"
+  phpmd_global_command="phpmd"
+  if [ -f "$phpmd_vendor_command" ]; then
+    phpmd_command=$phpmd_vendor_command
+  else
+    if hash phpmd 2>/dev/null; then
+      phpmd_command=$phpmd_global_command
     else
-        echo
-        message_success "✔ No PHPMD errors found!"
+      message_warning "No valid PHP Mess Detector executable found! Please have one available as either ✖✖✖ phpmd ✖✖✖"
+      message_info "Visit: https://phpmd.org/download/index.html"
+      echo
+      exit 1
     fi
+  fi
 
+  # @see https://phpmd.org/rules/index.html
+  phpmd_rules="cleancode,codesize,controversial,design,naming,unusedcode"
+
+  printf "✔︎ Report Format: ${color_bold_yellow}text${color_reset}\n"
+  printf "✔︎ Ruleset Files: ${color_bold_yellow}${phpmd_rules}${color_reset}\n"
+  printf "✔︎ Suffixes: ${color_bold_yellow}php${color_reset}\n"
+  echo
+
+  message_info "PHPMD - PHP Mess Detector: [ ${staged_files_separated_by_comma} ]"
+
+  # PHPMD running script
+  phpmd_output=$(${phpmd_command} ${staged_files_separated_by_comma} text "${phpmd_rules}" --suffixes php)
+  phpmd_retval=$?
+
+  if [ $phpmd_retval -ne 0 ]; then
     echo
-    echo "╭─────────────────────────────────────────────────╮"
-    printf "|〈〈〈 ${color_bold_white}PHP Copy/Paste Detector (PHPCPD)...${color_reset} 〉〉〉|\n"
-    echo "╰─────────────────────────────────────────────────╯"
+    message_failure "PHPMD - PHP Mess Detector found some errors. Fix the errors before commit."
+
+    printf "${phpmd_output}\n"
+
+    # Adding error message.
+    errors=("${errors[@]}" "$phpmd_output")
+  else
     echo
+    message_success "✔ No PHPMD errors found!"
+  fi
 
-    if ! hash phpcpd 2>/dev/null; then
-        message_warning "No valid PHP Copy/Paste Detector executable found! Please have one available as either ✖✖✖ phpcpd ✖✖✖"
-        printf "${color_bold_white}Please install phpcpd, e.g.:${color_reset}\n"
-        printf "${color_bold_green}composer global require --dev 'sebastian/phpcpd=*'${color_reset}\n"
-        echo
-        exit 1
-    fi
+  echo
+  echo "╭─────────────────────────────────────────────────╮"
+  printf "|〈〈〈 ${color_bold_white}PHP Copy/Paste Detector (PHPCPD)...${color_reset} 〉〉〉|\n"
+  echo "╰─────────────────────────────────────────────────╯"
+  echo
 
-    phpcpd_arguments="--no-interaction --progress --min-lines=3 --min-tokens=40"
+  phpcpd_command="phpcpd"
 
-    message_info "PHPCPD - PHP Copy/Paste Detector: [ ${staged_files_separated_by_spaces} ]"
-
-    # PHPCPD running script
-    phpcpd_tmp=/tmp/t$$
-    phpcpd ${phpcpd_arguments} ${staged_files_separated_by_spaces} > $phpcpd_tmp
-
-    if grep -q 'Found' $phpcpd_tmp
-    then
-        echo
-        echo
-        message_failure "PHPCPD - PHP Copy/Paste Detector found some errors. Fix the errors before commit."
-
-        echo
-        echo
-        phpcpd_output="`cat $phpcpd_tmp`"
-
-        printf "${phpcpd_output}\n"
-
-        # Adding error message.
-        errors=("${errors[@]}" "$phpcpd_output")
+  # Check vendor/bin/phpcpd
+  phpcpd_vendor_command="vendor/bin/phpcpd"
+  phpcpd_global_command="phpcpd"
+  if [ -f "$phpcpd_vendor_command" ]; then
+    phpcpd_command=$phpcpd_vendor_command
+  else
+    if hash phpcpd 2>/dev/null; then
+      phpcpd_command=$phpcpd_global_command
     else
-        echo
-        message_success "✔ No PHPCPD errors found!"
+      message_warning "No valid PHP Copy/Paste Detector executable found! Please have one available as either ✖✖✖ phpcpd ✖✖✖"
+      printf "${color_bold_white}Please install phpcpd, e.g.:${color_reset}\n"
+      printf "${color_bold_green}composer global require --dev 'sebastian/phpcpd=*'${color_reset}\n"
+      echo
+      exit 1
     fi
+  fi
 
-    # Cleanup
-    rm /tmp/*.$$ 2>/dev/null
-    rm /tmp/*$$.txt 2>/dev/null
-    rm -f $phpcpd_tmp
+  phpcpd_arguments="--no-interaction --progress --min-lines=3 --min-tokens=40"
+
+  message_info "PHPCPD - PHP Copy/Paste Detector: [ ${staged_files_separated_by_spaces} ]"
+
+  # PHPCPD running script
+  phpcpd_tmp=/tmp/t$$
+  ${phpcpd_command} ${phpcpd_arguments} ${staged_files_separated_by_spaces} >$phpcpd_tmp
+
+  if grep -q 'Found' $phpcpd_tmp; then
+    echo
+    echo
+    message_failure "PHPCPD - PHP Copy/Paste Detector found some errors. Fix the errors before commit."
+
+    echo
+    echo
+    phpcpd_output="$(cat $phpcpd_tmp)"
+
+    printf "${phpcpd_output}\n"
+
+    # Adding error message.
+    errors=("${errors[@]}" "$phpcpd_output")
+  else
+    echo
+    message_success "✔ No PHPCPD errors found!"
+  fi
+
+  # Cleanup
+  rm /tmp/*.$$ 2>/dev/null
+  rm /tmp/*$$.txt 2>/dev/null
+  rm -f $phpcpd_tmp
+
+  echo
+  echo "╭───────────────────────────────────────────╮"
+  printf "|〈〈〈 ${color_bold_white}Begin PHP Unit Task Runner...${color_reset} 〉〉〉|\n"
+  echo "╰───────────────────────────────────────────╯"
+  echo
+
+  phpunit_local_exec="phpunit.phar"
+  phpunit_command="php $phpunit_local_exec"
+
+  # Check vendor/bin/phpunit
+  phpunit_vendor_command="vendor/bin/phpunit"
+  phpunit_global_command="phpunit"
+  if [ -f "$phpunit_vendor_command" ]; then
+    phpunit_command=$phpunit_vendor_command
+  else
+    if hash phpunit 2>/dev/null; then
+      phpunit_command=$phpunit_global_command
+    else
+      if [ -f "$phpunit_local_exec" ]; then
+        phpunit_command=$phpunit_command
+      else
+        echo "No valid PHP Unit executable found! Please have one available as either $phpunit_vendor_command, $phpunit_global_command or $phpunit_local_exec"
+        exit 1
+      fi
+    fi
+  fi
+
+  echo "Running command $phpunit_command"
+  stdbuf -i0 -o0 -e0 $phpunit_command --testdox
+  if [ $? -ne 0 ]; then
+    echo "Failures detected in unit tests..."
+    echo "$command_result"
+    exit 1
+  fi
 
 fi
 
@@ -340,8 +394,8 @@ echo
 
 # If we have errors, exit with 1
 if [ -n "$errors" ]; then
-    message_failure 'Please check the terminal output and solve the errors!'
-    exit 1
+  message_failure 'Please check the terminal output and solve the errors!'
+  exit 1
 fi
 
 message_success 'No Errors Found 👏 👏 👏 👏 '
